version: "3.8"

services:
  app:
    image: kuanghaochina/distributed-key-kickoff:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
  master:
    image: redis
    ports:
      - "6379:6379"
  slave1:
    image: redis
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master
    ports:
      - "6380:6379"
  slave2:
    image: redis
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master
    ports:
      - "6381:6379"

  sentinel1:
    image: redis       ## 镜像
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf"
    links:
      - master:redis-master

  sentinel2:
    image: redis                ## 镜像
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf"
    links:
      - master:redis-master

  sentinel3:
    image: redis                ## 镜像
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - "./sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf"
    links:
      - master:redis-master