version: "3.8"

services:
  app:
    container_name: distributed-key-kickoff
    image: kuanghaochina/distributed-key-kickoff:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - 'SPRING_APPLICATION_JSON={"spring":{"application":{"name":"distributed-key-kickoff"},"config":{"location":"file:/config/"},"profiles":{"active":"redis-single"}}}'
    volumes:
      - ./distributed-key-kickoff:/config/
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"